"use strict";

var netgis = netgis || {};

netgis.Events = Object.freeze
(
	{
		CONTEXT_UPDATE: "CONTEXT_UPDATE",
		SET_MODE: "SET_MODE",
		
		LAYER_LIST_TOGGLE: "LAYER_LIST_TOGGLE",

		PANEL_TOGGLE: "PANEL_TOGGLE",
		PANEL_SHOW: "PANEL_SHOW",
		PANEL_HIDE: "PANEL_HIDE",

		LAYER_SHOW: "LAYER_SHOW",
		LAYER_HIDE: "LAYER_HIDE",
		LAYER_CREATED: "LAYER_CREATED",

		MAP_SET_EXTENT: "MAP_SET_EXTENT",
		MAP_CHANGE_ZOOM: "MAP_CHANGE_ZOOM",
		
		MAP_UPDATE_STYLE: "MAP_UPDATE_STYLE", //TODO: ?

		MAP_MODE_POINTS: "MAP_MODE_POINTS",
		MAP_MODE_LINES: "MAP_MODE_LINES",
		MAP_MODE_POLYGONS: "MAP_MODE_POLYGONS",
		
		EDIT_FEATURES_LOADED: "EDIT_FEATURES_LOADED",
		EDIT_FEATURES_CHANGE: "EDIT_FEATURES_CHANGE",
		
		SEARCH_PLACE_REQUEST: "SEARCH_PLACE_REQUEST",
		SEARCH_PLACE_RESPONSE: "SEARCH_PLACE_RESPONSE",
		
		BUFFER_CHANGE: "BUFFER_CHANGE",
		BUFFER_ACCEPT: "BUFFER_ACCEPT",
		BUFFER_CANCEL: "BUFFER_CANCEL",
		
		SNAP_ON: "SNAP_ON",
		SNAP_OFF: "SNAP_OFF",
		
		IMPORT_SHAPEFILE_SHOW: "IMPORT_SHAPEFILE_SHOW",
		IMPORT_GEOJSON_SHOW: "IMPORT_GEOJSON_SHOW",
		IMPORT_GML_SHOW: "IMPORT_GML_SHOW",
		
		IMPORT_SHAPEFILE: "IMPORT_SHAPEFILE",
		IMPORT_GEOJSON: "IMPORT_GEOJSON",
		IMPORT_GML: "IMPORT_GML",
		
		EXPORT_PDF_SHOW: "EXPORT_PDF_SHOW",
		EXPORT_JPEG_SHOW: "EXPORT_JPEG_SHOW",
		EXPORT_PNG_SHOW: "EXPORT_PNG_SHOW",
		EXPORT_GIF_SHOW: "EXPORT_GIF_SHOW",
		
		EXPORT_PDF: "EXPORT_PDF",
		EXPORT_JPEG: "EXPORT_JPEG",
		EXPORT_PNG: "EXPORT_PNG",
		EXPORT_GIF: "EXPORT_GIF",
		EXPORT_BEGIN: "EXPORT_BEGIN",
		EXPORT_END: "EXPORT_END"
	}
);
